/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkArea.Admin;

import Business.Professor.model.ProfessorDirectory;
import Business.Professor.model.Professor;
import java.awt.CardLayout;
import java.security.MessageDigest;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Hemant
 */
public class AdminCreateProfessorJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AdminCreateProfessorJPanel
     */
    private JPanel workAreaContainer;
    private ProfessorDirectory professorDirectory;
    public AdminCreateProfessorJPanel(JPanel workAreaContainer, ProfessorDirectory professorDirectory) {
        initComponents();
        this.workAreaContainer = workAreaContainer;
        this.professorDirectory = professorDirectory;
    }
    
       private boolean isValidPassword(String password) {
    if (password.length() < 6) {
        return false;
    }
    boolean hasNum = password.matches(".*\\d.*");
    boolean hasSpecial = !password.matches("[A-Za-z0-9]*");
    return hasNum && hasSpecial;
}
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtProfessorUserName = new javax.swing.JTextField();
        txtProfessorCountry = new javax.swing.JTextField();
        txtProfessorState = new javax.swing.JTextField();
        lblProfessorCity = new javax.swing.JLabel();
        lblProfessorState = new javax.swing.JLabel();
        lblProfessorGender = new javax.swing.JLabel();
        lblProfessorAge = new javax.swing.JLabel();
        lblProfessorCountry = new javax.swing.JLabel();
        lblProfessorContact = new javax.swing.JLabel();
        lblProfessorEmail = new javax.swing.JLabel();
        txtProfessorCity = new javax.swing.JTextField();
        txtProfessorAge = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        txtProfessorGender = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        txtProfessorEmail = new javax.swing.JTextField();
        txtProfessorContact = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtProfessorName = new javax.swing.JTextField();
        lblProfessorName = new javax.swing.JLabel();
        lblProfessorPassword = new javax.swing.JLabel();
        lblProfessorUserName = new javax.swing.JLabel();
        txtProfessorPassword = new javax.swing.JPasswordField();

        setBackground(new java.awt.Color(204, 204, 255));
        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        txtProfessorUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProfessorUserNameActionPerformed(evt);
            }
        });

        txtProfessorCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProfessorCountryActionPerformed(evt);
            }
        });

        txtProfessorState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProfessorStateActionPerformed(evt);
            }
        });

        lblProfessorCity.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblProfessorCity.setText("City : ");

        lblProfessorState.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblProfessorState.setText("State : ");

        lblProfessorGender.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblProfessorGender.setText("Gender : ");

        lblProfessorAge.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblProfessorAge.setText("Age : ");

        lblProfessorCountry.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblProfessorCountry.setText("Country : ");

        lblProfessorContact.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblProfessorContact.setText("Contact Number : ");

        lblProfessorEmail.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblProfessorEmail.setText("E-mail Id : ");

        txtProfessorCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProfessorCityActionPerformed(evt);
            }
        });

        txtProfessorAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProfessorAgeActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(204, 204, 204), new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204)));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        txtProfessorGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProfessorGenderActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(204, 204, 204), new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204)));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        txtProfessorEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProfessorEmailActionPerformed(evt);
            }
        });

        txtProfessorContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProfessorContactActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(153, 153, 153));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Create Professor Account");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), null, null));

        txtProfessorName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProfessorNameActionPerformed(evt);
            }
        });

        lblProfessorName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblProfessorName.setText("Name : ");

        lblProfessorPassword.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblProfessorPassword.setText("Password : ");

        lblProfessorUserName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblProfessorUserName.setText("User name : ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(464, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblProfessorPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblProfessorUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(36, 36, 36)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtProfessorUserName, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                                .addComponent(txtProfessorPassword)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblProfessorAge, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblProfessorName, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblProfessorGender, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblProfessorEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblProfessorContact, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(36, 36, 36)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtProfessorName, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtProfessorContact, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtProfessorEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtProfessorGender, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtProfessorAge, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblProfessorCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblProfessorState, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblProfessorCity, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(40, 40, 40)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtProfessorState, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtProfessorCity, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtProfessorCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(526, 526, 526))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtProfessorName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProfessorName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProfessorAge, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProfessorAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProfessorGender, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProfessorGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProfessorEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProfessorEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProfessorContact, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProfessorContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProfessorUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProfessorUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProfessorPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProfessorPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProfessorCity, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProfessorCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProfessorState, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProfessorState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProfessorCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProfessorCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(173, Short.MAX_VALUE))
        );

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void txtProfessorUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProfessorUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProfessorUserNameActionPerformed

    private void txtProfessorAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProfessorAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProfessorAgeActionPerformed

    private void txtProfessorGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProfessorGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProfessorGenderActionPerformed

    private void txtProfessorEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProfessorEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProfessorEmailActionPerformed

    private void txtProfessorContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProfessorContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProfessorContactActionPerformed

    private void txtProfessorNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProfessorNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProfessorNameActionPerformed

    private void txtProfessorCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProfessorCountryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProfessorCountryActionPerformed

    private void txtProfessorStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProfessorStateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProfessorStateActionPerformed

    private void txtProfessorCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProfessorCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProfessorCityActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        workAreaContainer.remove(this);
        CardLayout layout = (CardLayout) workAreaContainer.getLayout();
        layout.previous(workAreaContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
    // Retrieve the input values from the text fields
    String name = txtProfessorName.getText();
    String age = txtProfessorAge.getText();
    String gender = txtProfessorGender.getText();
    String email = txtProfessorEmail.getText();
    String contact = txtProfessorContact.getText();
    String username = txtProfessorUserName.getText();
    String password = new String(txtProfessorPassword.getPassword());
    String city = txtProfessorCity.getText();
    String state = txtProfessorState.getText();
    String country = txtProfessorCountry.getText();

    // Validation of input fields
    if (name.isEmpty() || age.isEmpty() || gender.isEmpty() || email.isEmpty() || contact.isEmpty() || username.isEmpty() || password.isEmpty() || city.isEmpty() || state.isEmpty() || country.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Please fill in all fields.");
        return;
    }

    // Validate password
    if (!isValidPassword(password)) {
        JOptionPane.showMessageDialog(null, "Password must be at least 6 characters long, include at least 1 special character and 1 number.");
        return;
    }

    // Check for existing professor with the same name, email, or username
    boolean isDuplicate = professorDirectory.isDuplicateProfessor(name, email, username, null);
    if (isDuplicate) {
        JOptionPane.showMessageDialog(null, "Duplicate professor details found. Please ensure the name, email, and username are unique.");
        return;
    }

    // Create new professor
    Professor professor = professorDirectory.addProfessor();
    professor.setName(name);
    professor.setAge(age);
    professor.setGender(gender);
    professor.setEmail(email);
    professor.setContact(contact);
    professor.setUsername(username);
    professor.setPassword(password); 
    professor.setCity(city);
    professor.setState(state);
    professor.setCountry(country);

    JOptionPane.showMessageDialog(null, "Professor Profile Created");

    // Clear the input fields
    txtProfessorName.setText("");
    txtProfessorAge.setText("");
    txtProfessorGender.setText("");
    txtProfessorEmail.setText("");
    txtProfessorContact.setText("");
    txtProfessorUserName.setText("");
    txtProfessorPassword.setText("");
    txtProfessorCity.setText("");
    txtProfessorState.setText("");
    txtProfessorCountry.setText("");


    
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblProfessorAge;
    private javax.swing.JLabel lblProfessorCity;
    private javax.swing.JLabel lblProfessorContact;
    private javax.swing.JLabel lblProfessorCountry;
    private javax.swing.JLabel lblProfessorEmail;
    private javax.swing.JLabel lblProfessorGender;
    private javax.swing.JLabel lblProfessorName;
    private javax.swing.JLabel lblProfessorPassword;
    private javax.swing.JLabel lblProfessorState;
    private javax.swing.JLabel lblProfessorUserName;
    private javax.swing.JTextField txtProfessorAge;
    private javax.swing.JTextField txtProfessorCity;
    private javax.swing.JTextField txtProfessorContact;
    private javax.swing.JTextField txtProfessorCountry;
    private javax.swing.JTextField txtProfessorEmail;
    private javax.swing.JTextField txtProfessorGender;
    private javax.swing.JTextField txtProfessorName;
    private javax.swing.JPasswordField txtProfessorPassword;
    private javax.swing.JTextField txtProfessorState;
    private javax.swing.JTextField txtProfessorUserName;
    // End of variables declaration//GEN-END:variables

    private String hashPassword(String password) { 
    try {
        MessageDigest md = MessageDigest.getInstance("SHA-1"); // Consider using "SHA-256"
        md.update(password.getBytes());
        byte[] rbt = md.digest();
        StringBuilder pass = new StringBuilder();
        for (byte b : rbt) {
            pass.append(String.format("%02x", b));
        }
        return pass.toString(); 
    } catch (Exception ex) {  
        ex.printStackTrace();
    }
    return null;
}

}
