/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkArea.Admin;

import Business.Authority.AuthorityDirectory;
import Business.Authority.AuthorityModel;
import java.awt.CardLayout;
import java.security.MessageDigest;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Hemant
 */
public class AdminCreateAuthority extends javax.swing.JPanel {

    /**
     * Creates new form AdminCreateAuthority
     */
    private JPanel workAreaContainer;
    private AuthorityDirectory authorityDirectory;
    public AdminCreateAuthority(JPanel workAreaContainer, AuthorityDirectory authorityDirectory) {
        initComponents();
        this.workAreaContainer = workAreaContainer;
        this.authorityDirectory = authorityDirectory;
    }
    
           private boolean isValidPassword(String password) {
    if (password.length() < 6) {
        return false;
    }
    boolean hasNum = password.matches(".*\\d.*");
    boolean hasSpecial = !password.matches("[A-Za-z0-9]*");
    return hasNum && hasSpecial;
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtAuthorityName = new javax.swing.JTextField();
        lblAuthorityName = new javax.swing.JLabel();
        lblAuthorityCompany = new javax.swing.JLabel();
        lblEmployerPassword = new javax.swing.JLabel();
        lblEmployerUserName = new javax.swing.JLabel();
        txtAuthorityCompany = new javax.swing.JTextField();
        txtAuthorityUsername = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtAuthorityPassword = new javax.swing.JPasswordField();

        setBackground(new java.awt.Color(204, 204, 255));
        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        txtAuthorityName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAuthorityNameActionPerformed(evt);
            }
        });

        lblAuthorityName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblAuthorityName.setText("Name : ");

        lblAuthorityCompany.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblAuthorityCompany.setText("Company : ");

        lblEmployerPassword.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEmployerPassword.setText("Password : ");

        lblEmployerUserName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEmployerUserName.setText("User Name : ");

        txtAuthorityCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAuthorityCompanyActionPerformed(evt);
            }
        });

        txtAuthorityUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAuthorityUsernameActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(204, 204, 204), new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204)));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(204, 204, 204), new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204)));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(153, 153, 153));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Create Authority Account");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), null, null));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lblAuthorityName, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(36, 36, 36)
                                    .addComponent(txtAuthorityName, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lblAuthorityCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(36, 36, 36)
                                    .addComponent(txtAuthorityCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblEmployerUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblEmployerPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(36, 36, 36)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtAuthorityUsername)
                                        .addComponent(txtAuthorityPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 842, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAuthorityName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAuthorityName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAuthorityCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAuthorityCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEmployerUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAuthorityUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmployerPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAuthorityPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(300, Short.MAX_VALUE))
        );

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void txtAuthorityNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAuthorityNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAuthorityNameActionPerformed

    private void txtAuthorityCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAuthorityCompanyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAuthorityCompanyActionPerformed

    private void txtAuthorityUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAuthorityUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAuthorityUsernameActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        workAreaContainer.remove(this);
        CardLayout layout = (CardLayout) workAreaContainer.getLayout();
        layout.previous(workAreaContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
         String name = txtAuthorityName.getText();
         String company = txtAuthorityCompany.getText();
         String username = txtAuthorityUsername.getText();
         String password = new String(txtAuthorityPassword.getPassword());
         
             // Validation of input fields
    if (name.isEmpty() || company.isEmpty() || username.isEmpty() || password.isEmpty() ) {
        JOptionPane.showMessageDialog(null, "Please fill in all fields.");
        return;
    }
    
        // Validate password
    if (!isValidPassword(password)) {
        JOptionPane.showMessageDialog(null, "Password must be at least 6 characters long, include at least 1 special character and 1 number.");
        return;
    }
    
        // Check for existing employer with the same name, email, or username
    boolean isDuplicate = authorityDirectory.isDuplicateAuthority(name, username, null);
    if (isDuplicate) {
        JOptionPane.showMessageDialog(null, "Duplicate 3rd-party authority details found. Please ensure the name and username are unique.");
        return;
    }
         
    // Create new Authority
         AuthorityModel authority = authorityDirectory.addAuthority();
         authority.setCompany(company);
         authority.setName(name);
         authority.setUsername(username);
         authority.setPassword(password);
         
                  JOptionPane.showMessageDialog(null, "Authority Profile Created");

          txtAuthorityName.setText("");
         txtAuthorityCompany.setText("");
         txtAuthorityUsername.setText("");
         txtAuthorityPassword.setText("");
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAuthorityCompany;
    private javax.swing.JLabel lblAuthorityName;
    private javax.swing.JLabel lblEmployerPassword;
    private javax.swing.JLabel lblEmployerUserName;
    private javax.swing.JTextField txtAuthorityCompany;
    private javax.swing.JTextField txtAuthorityName;
    private javax.swing.JPasswordField txtAuthorityPassword;
    private javax.swing.JTextField txtAuthorityUsername;
    // End of variables declaration//GEN-END:variables

        private String hashPassword(String password) { 
    try {
        MessageDigest md = MessageDigest.getInstance("SHA-1"); // Consider using "SHA-256"
        md.update(password.getBytes());
        byte[] rbt = md.digest();
        StringBuilder pass = new StringBuilder();
        for (byte b : rbt) {
            pass.append(String.format("%02x", b));
        }
        return pass.toString(); 
    } catch (Exception ex) {  
        ex.printStackTrace();
    }
    return null;
}

}
