/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkArea.Admin;

import Business.Authority.AuthorityDirectory;
import Business.Employer.EmployerDirectory;
import Business.Professor.model.ProfessorDirectory;
import Business.Student.model.StudentDirectory;
import Business.Student.model.Student;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Hemant
 */
public class adminHomePageJPanel extends javax.swing.JPanel {

    /**
     * Creates new form adminHomePageJPanel
     */
    private JPanel workAreaContainer;
    private StudentDirectory studentDirectory;
    private ProfessorDirectory professorDirectory;
    private EmployerDirectory employerDirectory;
    private AuthorityDirectory authorityDirectory;
    public adminHomePageJPanel(JPanel workAreaContainer,ProfessorDirectory professorDirectory,StudentDirectory studentDirectory,EmployerDirectory employerDirectory,AuthorityDirectory authorityDirectory) {
        initComponents();
        this.studentDirectory = studentDirectory;
        this.workAreaContainer = workAreaContainer;
        this.professorDirectory = professorDirectory;
        this.employerDirectory = employerDirectory;
        this.authorityDirectory = authorityDirectory;
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnCreateStudent = new javax.swing.JButton();
        btnCreateProfessor = new javax.swing.JButton();
        btnCreateEmployer = new javax.swing.JButton();
        btnCreateAuthority = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnUpdateEmployer = new javax.swing.JButton();
        btnUpdateAuthority = new javax.swing.JButton();
        btnUpdateStudent = new javax.swing.JButton();
        btnUpdateProfessor = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setBackground(new java.awt.Color(255, 255, 204));

        btnCreateStudent.setText("Create Student profile");
        btnCreateStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateStudentActionPerformed(evt);
            }
        });

        btnCreateProfessor.setText("Create Professor profile");
        btnCreateProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateProfessorActionPerformed(evt);
            }
        });

        btnCreateEmployer.setText("Create Employer profile");
        btnCreateEmployer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateEmployerActionPerformed(evt);
            }
        });

        btnCreateAuthority.setText("Create Authority profile");
        btnCreateAuthority.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAuthorityActionPerformed(evt);
            }
        });

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnUpdateEmployer.setText("Update/Delete Employer profile");
        btnUpdateEmployer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateEmployerActionPerformed(evt);
            }
        });

        btnUpdateAuthority.setText("Update/Delete Authority profile");
        btnUpdateAuthority.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateAuthorityActionPerformed(evt);
            }
        });

        btnUpdateStudent.setText("Update/Delete Student profile");
        btnUpdateStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateStudentActionPerformed(evt);
            }
        });

        btnUpdateProfessor.setText("Update/Delete Professor profile");
        btnUpdateProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateProfessorActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(153, 153, 153));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(" Admin Dashboard");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), null, null));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1352, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(446, 446, 446)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCreateAuthority, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCreateEmployer, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCreateProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCreateStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnUpdateEmployer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnUpdateAuthority, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnUpdateProfessor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnUpdateStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCreateStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCreateProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCreateEmployer, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btnCreateAuthority, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnUpdateStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdateProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdateEmployer, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btnUpdateAuthority, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(237, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        workAreaContainer.remove(this);
        CardLayout layout = (CardLayout) workAreaContainer.getLayout();
        layout.previous(workAreaContainer);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnCreateStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateStudentActionPerformed
        // TODO add your handling code here:
        AdminCreateStudentJPanel panel = new AdminCreateStudentJPanel(workAreaContainer, studentDirectory);
        workAreaContainer.add("AdminCreateStudentJPanel", panel);
        CardLayout layout = (CardLayout) workAreaContainer.getLayout();
        layout.next(workAreaContainer);
    }//GEN-LAST:event_btnCreateStudentActionPerformed

    private void btnCreateProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateProfessorActionPerformed
        // TODO add your handling code here:
        AdminCreateProfessorJPanel panel = new AdminCreateProfessorJPanel(workAreaContainer, professorDirectory);
        workAreaContainer.add("AdminCreateProfessorJPanel", panel);
        CardLayout layout = (CardLayout) workAreaContainer.getLayout();
        layout.next(workAreaContainer);
    }//GEN-LAST:event_btnCreateProfessorActionPerformed

    private void btnCreateEmployerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateEmployerActionPerformed
        // TODO add your handling code here:
        AdminCreateEmployer panel = new AdminCreateEmployer(workAreaContainer, employerDirectory);
        workAreaContainer.add("AdminCreateEmployer", panel);
        CardLayout layout = (CardLayout) workAreaContainer.getLayout();
        layout.next(workAreaContainer);
    }//GEN-LAST:event_btnCreateEmployerActionPerformed

    private void btnCreateAuthorityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAuthorityActionPerformed
        // TODO add your handling code here:
        AdminCreateAuthority panel = new AdminCreateAuthority(workAreaContainer, authorityDirectory);
        workAreaContainer.add("AdminCreateAuthority", panel);
        CardLayout layout = (CardLayout) workAreaContainer.getLayout();
        layout.next(workAreaContainer);
    }//GEN-LAST:event_btnCreateAuthorityActionPerformed

    private void btnUpdateEmployerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateEmployerActionPerformed
        // TODO add your handling code here:
        AdminUpdateEmployerJPanel panel = new AdminUpdateEmployerJPanel(workAreaContainer, employerDirectory);
        workAreaContainer.add("AdminUpdateEmployerJPanel", panel);
        CardLayout layout = (CardLayout) workAreaContainer.getLayout();
        layout.next(workAreaContainer);
    }//GEN-LAST:event_btnUpdateEmployerActionPerformed

    private void btnUpdateAuthorityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateAuthorityActionPerformed
        // TODO add your handling code here:
        AdminUpdateAuthorityJPanel panel = new AdminUpdateAuthorityJPanel(workAreaContainer, authorityDirectory);
        workAreaContainer.add("AuthorityUpdateEmployerJPanel", panel);
        CardLayout layout = (CardLayout) workAreaContainer.getLayout();
        layout.next(workAreaContainer);
    }//GEN-LAST:event_btnUpdateAuthorityActionPerformed

    private void btnUpdateStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateStudentActionPerformed
        // TODO add your handling code here:
        AdminUpdateStudentJPanel panel = new AdminUpdateStudentJPanel(workAreaContainer, studentDirectory);
        workAreaContainer.add("AdminUpdateStudentJPanel", panel);
        CardLayout layout = (CardLayout) workAreaContainer.getLayout();
        layout.next(workAreaContainer);
        
    }//GEN-LAST:event_btnUpdateStudentActionPerformed

    private void btnUpdateProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateProfessorActionPerformed
        // TODO add your handling code here:
        AdminUpdateProfessorJPanel panel = new AdminUpdateProfessorJPanel(workAreaContainer, professorDirectory);
        workAreaContainer.add("AdminUpdateProfessorJPanel", panel);
        CardLayout layout = (CardLayout) workAreaContainer.getLayout();
        layout.next(workAreaContainer);
    }//GEN-LAST:event_btnUpdateProfessorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateAuthority;
    private javax.swing.JButton btnCreateEmployer;
    private javax.swing.JButton btnCreateProfessor;
    private javax.swing.JButton btnCreateStudent;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnUpdateAuthority;
    private javax.swing.JButton btnUpdateEmployer;
    private javax.swing.JButton btnUpdateProfessor;
    private javax.swing.JButton btnUpdateStudent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
