/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkArea.Admin;

import Business.Employer.EmployerDirectory;
import Business.Employer.EmployerModel;
import java.awt.CardLayout;
import java.security.MessageDigest;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Hemant
 */
public class AdminCreateEmployer extends javax.swing.JPanel {

    /**
     * Creates new form AdminCreateEmployer
     */
    private JPanel workAreaContainer;
    private EmployerDirectory employerDirectory;
    public AdminCreateEmployer(JPanel workAreaContainer, EmployerDirectory employerDirectory) {
        initComponents();
        this.workAreaContainer = workAreaContainer;
        this.employerDirectory = employerDirectory;
        
    }
    
    
           private boolean isValidPassword(String password) {
    if (password.length() < 6) {
        return false;
    }
    boolean hasNum = password.matches(".*\\d.*");
    boolean hasSpecial = !password.matches("[A-Za-z0-9]*");
    return hasNum && hasSpecial;
}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblEmployerEmail = new javax.swing.JLabel();
        txtEmployerEmail = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        txtEmployerCompany = new javax.swing.JTextField();
        txtEmployerDesignation = new javax.swing.JTextField();
        txtEmployerUserId = new javax.swing.JTextField();
        lblEmployerPassword = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblEmployerName = new javax.swing.JLabel();
        lblEmployerDesignation = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        txtEmployerLocation = new javax.swing.JTextField();
        txtEmployerName = new javax.swing.JTextField();
        lblEmployerCompany = new javax.swing.JLabel();
        lblEmployerUserName = new javax.swing.JLabel();
        lblEmployerLocation = new javax.swing.JLabel();
        txtEmployerPassword = new javax.swing.JPasswordField();

        setBackground(new java.awt.Color(204, 255, 204));
        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        lblEmployerEmail.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEmployerEmail.setText("E-mail Id : ");

        txtEmployerEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmployerEmailActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(204, 204, 204), new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204)));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        txtEmployerCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmployerCompanyActionPerformed(evt);
            }
        });

        txtEmployerDesignation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmployerDesignationActionPerformed(evt);
            }
        });

        txtEmployerUserId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmployerUserIdActionPerformed(evt);
            }
        });

        lblEmployerPassword.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEmployerPassword.setText("Password : ");

        jLabel1.setBackground(new java.awt.Color(153, 153, 153));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Create Employer Account");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), null, null));

        lblEmployerName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEmployerName.setText("Name : ");

        lblEmployerDesignation.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEmployerDesignation.setText("Designation : ");

        btnSave.setText("Save");
        btnSave.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(204, 204, 204), new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204)));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        txtEmployerLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmployerLocationActionPerformed(evt);
            }
        });

        txtEmployerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmployerNameActionPerformed(evt);
            }
        });

        lblEmployerCompany.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEmployerCompany.setText("Company : ");

        lblEmployerUserName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEmployerUserName.setText("User Name : ");

        lblEmployerLocation.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEmployerLocation.setText("Location : ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(489, 489, 489)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEmployerName, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEmployerEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEmployerLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmployerName, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmployerLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmployerEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblEmployerCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(txtEmployerCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblEmployerDesignation, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblEmployerUserName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblEmployerPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtEmployerUserId, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                            .addComponent(txtEmployerDesignation, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                            .addComponent(txtEmployerPassword))))
                .addContainerGap(501, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEmployerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmployerName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmployerCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmployerCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmployerEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmployerEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmployerLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmployerLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmployerDesignation, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmployerDesignation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEmployerUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmployerUserId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEmployerPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmployerPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(220, Short.MAX_VALUE))
        );

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmployerEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmployerEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmployerEmailActionPerformed

    private void txtEmployerCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmployerCompanyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmployerCompanyActionPerformed

    private void txtEmployerDesignationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmployerDesignationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmployerDesignationActionPerformed

    private void txtEmployerUserIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmployerUserIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmployerUserIdActionPerformed

    private void txtEmployerLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmployerLocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmployerLocationActionPerformed

    private void txtEmployerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmployerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmployerNameActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        workAreaContainer.remove(this);
        CardLayout layout = (CardLayout) workAreaContainer.getLayout();
        layout.previous(workAreaContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
         String name = txtEmployerName.getText();
         String company = txtEmployerCompany.getText();
         String emailID = txtEmployerEmail.getText();
         String location = txtEmployerLocation.getText();
         String designation = txtEmployerDesignation.getText();
         String username = txtEmployerUserId.getText();
         String password = new String(txtEmployerPassword.getPassword());
         
         // Validation of input fields
    if (name.isEmpty() || company.isEmpty() || emailID.isEmpty() || location.isEmpty() || designation.isEmpty() || username.isEmpty() || password.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Please fill in all fields.");
        return;
    }

    // Validate password
    if (!isValidPassword(password)) {
        JOptionPane.showMessageDialog(null, "Password must be at least 6 characters long, include at least 1 special character and 1 number.");
        return;
    }

    // Check for duplicate employer details
    if (employerDirectory.isDuplicateEmployer(name, emailID, username, null)) {
        JOptionPane.showMessageDialog(null, "An employer with the same name, email, or username already exists.");
        return;
    }
         // Create new employer
         EmployerModel employer = employerDirectory.addEmployer();
         employer.setName(name);
         employer.setCompany(company);
         employer.setEmailID(emailID);
         employer.setLocation(location);
         employer.setDesignation(designation);
         employer.setUsername(username);
         employer.setPassword(password);
         
        JOptionPane.showMessageDialog(null, "Employer Profile Created");
        
         txtEmployerName.setText("");
         txtEmployerCompany.setText("");
         txtEmployerEmail.setText("");
         txtEmployerLocation.setText("");
         txtEmployerDesignation.setText("");
         txtEmployerUserId.setText("");
         txtEmployerPassword.setText("");
         
         
         
        
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblEmployerCompany;
    private javax.swing.JLabel lblEmployerDesignation;
    private javax.swing.JLabel lblEmployerEmail;
    private javax.swing.JLabel lblEmployerLocation;
    private javax.swing.JLabel lblEmployerName;
    private javax.swing.JLabel lblEmployerPassword;
    private javax.swing.JLabel lblEmployerUserName;
    private javax.swing.JTextField txtEmployerCompany;
    private javax.swing.JTextField txtEmployerDesignation;
    private javax.swing.JTextField txtEmployerEmail;
    private javax.swing.JTextField txtEmployerLocation;
    private javax.swing.JTextField txtEmployerName;
    private javax.swing.JPasswordField txtEmployerPassword;
    private javax.swing.JTextField txtEmployerUserId;
    // End of variables declaration//GEN-END:variables

    
        private String hashPassword(String password) { 
    try {
        MessageDigest md = MessageDigest.getInstance("SHA-1"); // Consider using "SHA-256"
        md.update(password.getBytes());
        byte[] rbt = md.digest();
        StringBuilder pass = new StringBuilder();
        for (byte b : rbt) {
            pass.append(String.format("%02x", b));
        }
        return pass.toString(); 
    } catch (Exception ex) {  
        ex.printStackTrace();
    }
    return null;
}

}
