/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.Professor.ui;

import Business.Professor.model.Course;
import Business.Professor.model.CourseHistory;
import Business.Professor.model.Professor;
import Business.Professor.model.ProfessorDirectory;
import java.awt.CardLayout;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Hemant
 */
public class AddCourseJPanel extends javax.swing.JPanel {

    //This variable stores JPanel workAreaContainer
    private JPanel workAreaContainer;
    
    //This variable stores professor directory
    private ProfessorDirectory professorDirectory;
    
    //This variable stores professor
    private Professor professor;
    
    /**
     * Creates new form AddCourseJPanel
     */
    public AddCourseJPanel() {
        initComponents();
    }

    
    public AddCourseJPanel(  JPanel workAreaContainer,Professor professor, ProfessorDirectory professorDirectory) {
        initComponents();
        this.workAreaContainer = workAreaContainer;
        this.professor=professor;
        this.professorDirectory = professorDirectory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtAddCourse = new javax.swing.JLabel();
        lblCourseName = new javax.swing.JLabel();
        txtCourseName = new javax.swing.JTextField();
        lblStartDate = new javax.swing.JLabel();
        lblEndDate = new javax.swing.JLabel();
        lblDay = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        txtStartDate = new javax.swing.JTextField();
        txtEndDate = new javax.swing.JTextField();
        txtDay = new javax.swing.JTextField();
        txtTime = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblTime1 = new javax.swing.JLabel();
        isCompleted = new javax.swing.JCheckBox();
        lblCrn = new javax.swing.JLabel();
        txtCrn = new javax.swing.JTextField();
        lblLanguage = new javax.swing.JLabel();
        lblRegion = new javax.swing.JLabel();
        cbRegion = new javax.swing.JComboBox<>();
        cbLanguage = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(204, 255, 255));

        txtAddCourse.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        txtAddCourse.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtAddCourse.setText("Add Course");
        txtAddCourse.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblCourseName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCourseName.setText("Course Name:");

        lblStartDate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblStartDate.setText("Start Date:");

        lblEndDate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblEndDate.setText("End Date:");

        lblDay.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDay.setText("Day:");

        lblTime.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTime.setText("Time:");

        txtEndDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEndDateActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(255, 204, 204));
        btnBack.setText("<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblTime1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTime1.setText("Completed:");

        lblCrn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCrn.setText("CRN:");

        txtCrn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCrnActionPerformed(evt);
            }
        });

        lblLanguage.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblLanguage.setText("Language:");

        lblRegion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRegion.setText("Region:");

        cbRegion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Boston", "Seattle", "London", "Toronto", "Silicon Valley", "Remote" }));

        cbLanguage.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "English", "Spanish", "Japanese", "German" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTime1)
                            .addComponent(lblTime)
                            .addComponent(lblCourseName)
                            .addComponent(lblStartDate)
                            .addComponent(lblEndDate)
                            .addComponent(lblDay)
                            .addComponent(lblCrn)
                            .addComponent(lblLanguage)
                            .addComponent(lblRegion))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(isCompleted)
                            .addComponent(txtCrn)
                            .addComponent(txtTime)
                            .addComponent(txtDay)
                            .addComponent(txtEndDate)
                            .addComponent(txtStartDate)
                            .addComponent(txtCourseName)
                            .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbRegion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtAddCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtAddCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCrn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCrn, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCourseName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStartDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEndDate)
                    .addComponent(txtEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDay)
                    .addComponent(txtDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTime)
                    .addComponent(txtTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLanguage)
                    .addComponent(cbLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRegion)
                    .addComponent(cbRegion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTime1)
                    .addComponent(isCompleted))
                .addGap(18, 18, 18)
                .addComponent(btnSave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
         String crn = txtCrn.getText();
         String courseName = txtCourseName.getText();
         String startDate = txtStartDate.getText();
         String endDate = txtEndDate.getText();
         String day = txtDay.getText();
         String time = txtTime.getText();
         String language=(String)cbLanguage.getSelectedItem();
         String region=(String)cbRegion.getSelectedItem();
         Boolean completed=isCompleted.isSelected();
         int crnUnique=0;
         Set<Integer> usedCRNs = new HashSet<>();
         for (Professor professor : professorDirectory.getProfessorList()) {
         for (Course course : professor.getCourseHistory().getCourseList()) {
         crnUnique = course.getCRN();
          usedCRNs.add(crnUnique);
           }
         }
        if (usedCRNs.contains(Integer.parseInt(crn))) {
            // CRN is already used, handle this case as needed
          JOptionPane.showMessageDialog(null, "Course CRN already used.");
        } else {
            Course course=new Course();
         course.setCRN(Integer.parseInt(crn));
         course.setCourseName(courseName);
         course.setStartDate(startDate);
         course.setEndDate(endDate);
         course.setDay(day);
         course.setTime(time);
         course.setLanguage(language);
         course.setRegion(region);
         course.setCompleted(completed);
         course.setProfName(professor.getName());
         course.setProfRepo(professor.getReputation());
         CourseHistory courseHistory=professor.getCourseHistory();
         courseHistory.addCourse(course);
         professor.setCourseHistory(courseHistory);
         txtCourseName.setText("");
         txtStartDate.setText("");
         txtEndDate.setText("");
         txtDay.setText("");
         txtTime.setText("");
         txtCrn.setText("");
         isCompleted.setSelected(false);
          JOptionPane.showMessageDialog(null, "Course Added Successfully.");
      
        }
         
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        workAreaContainer.remove(this);
        CardLayout layout = (CardLayout) workAreaContainer.getLayout();
        layout.previous(workAreaContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtEndDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEndDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEndDateActionPerformed

    private void txtCrnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCrnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCrnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cbLanguage;
    private javax.swing.JComboBox<String> cbRegion;
    private javax.swing.JCheckBox isCompleted;
    private javax.swing.JLabel lblCourseName;
    private javax.swing.JLabel lblCrn;
    private javax.swing.JLabel lblDay;
    private javax.swing.JLabel lblEndDate;
    private javax.swing.JLabel lblLanguage;
    private javax.swing.JLabel lblRegion;
    private javax.swing.JLabel lblStartDate;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblTime1;
    private javax.swing.JLabel txtAddCourse;
    private javax.swing.JTextField txtCourseName;
    private javax.swing.JTextField txtCrn;
    private javax.swing.JTextField txtDay;
    private javax.swing.JTextField txtEndDate;
    private javax.swing.JTextField txtStartDate;
    private javax.swing.JTextField txtTime;
    // End of variables declaration//GEN-END:variables
}
