/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.Professor.ui;

import Business.Professor.model.Professor;
import Business.Professor.model.ProfessorDirectory;
import Business.Student.model.StudentDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Hemant
 */
public class ProfessorViewUpdateJPanel extends javax.swing.JPanel {

    //This variable stores JPanel workAreaContainer
    private JPanel workAreaContainer;

    //This variable stores Professor directory
    private ProfessorDirectory professorDirectory;

    //This variable stores Professor 
    private Professor professor;

    /**
     * Creates new form ProfessorViewUpdateJPanel
     */
    public ProfessorViewUpdateJPanel() {
        initComponents();
    }

    public ProfessorViewUpdateJPanel(JPanel workAreaContainer, Professor professor, ProfessorDirectory professorDirectory) {
        initComponents();
        this.workAreaContainer = workAreaContainer;
        this.professor = professor;
        this.professorDirectory = professorDirectory;

        txtProfessorName.setText(professor.getName());
        txtProfessorAge.setText(professor.getAge());
        txtProfessorGender.setText(professor.getGender());
        txtProfessorEmail.setText(professor.getEmail());
        txtProfessorContact.setText(professor.getContact());
        txtProfessorUserName.setText(professor.getUsername());
        txtProfessorPassword.setText("(Password encrypted)");
        txtProfessorPassword.setEchoChar((char) 0);
        txtProfessorPassword.setEditable(false);
        txtProfessorCity.setText(professor.getCity());
        txtProfessorState.setText(professor.getState());
        txtProfessorCountry.setText(professor.getCountry());
//        txtProfessorRepo.setText(professor.getReputation());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtProfessorEmail = new javax.swing.JTextField();
        lblStudentContact = new javax.swing.JLabel();
        txtProfessorContact = new javax.swing.JTextField();
        lblStudentUserName = new javax.swing.JLabel();
        txtProfessorUserName = new javax.swing.JTextField();
        lblStudentPassword = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblStudentCity = new javax.swing.JLabel();
        txtProfessorCity = new javax.swing.JTextField();
        lblStudentState = new javax.swing.JLabel();
        txtProfessorState = new javax.swing.JTextField();
        lblStudentCountry = new javax.swing.JLabel();
        txtProfessorCountry = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        lblProfessorName = new javax.swing.JLabel();
        txtProfessorName = new javax.swing.JTextField();
        txtProfessorAge = new javax.swing.JTextField();
        lblStudentAge = new javax.swing.JLabel();
        lblStudentGender = new javax.swing.JLabel();
        txtProfessorGender = new javax.swing.JTextField();
        lblStudentEmail = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        cbShowPassword = new javax.swing.JCheckBox();
        txtProfessorPassword = new javax.swing.JPasswordField();

        setBackground(new java.awt.Color(204, 255, 255));

        txtProfessorEmail.setEnabled(false);
        txtProfessorEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProfessorEmailActionPerformed(evt);
            }
        });

        lblStudentContact.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblStudentContact.setText("Contact Number : ");

        txtProfessorContact.setEnabled(false);
        txtProfessorContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProfessorContactActionPerformed(evt);
            }
        });

        lblStudentUserName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblStudentUserName.setText("User Name : ");

        txtProfessorUserName.setEnabled(false);
        txtProfessorUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProfessorUserNameActionPerformed(evt);
            }
        });

        lblStudentPassword.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblStudentPassword.setText("Password : ");

        jLabel1.setBackground(new java.awt.Color(153, 153, 153));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("View Professor Profile");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), null, null));

        lblStudentCity.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblStudentCity.setText("City : ");

        txtProfessorCity.setEnabled(false);
        txtProfessorCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProfessorCityActionPerformed(evt);
            }
        });

        lblStudentState.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblStudentState.setText("State : ");

        txtProfessorState.setEnabled(false);
        txtProfessorState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProfessorStateActionPerformed(evt);
            }
        });

        lblStudentCountry.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblStudentCountry.setText("Country : ");

        txtProfessorCountry.setEnabled(false);
        txtProfessorCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProfessorCountryActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.setEnabled(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lblProfessorName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblProfessorName.setText("Name : ");

        txtProfessorName.setEnabled(false);
        txtProfessorName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProfessorNameActionPerformed(evt);
            }
        });

        txtProfessorAge.setEnabled(false);
        txtProfessorAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProfessorAgeActionPerformed(evt);
            }
        });

        lblStudentAge.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblStudentAge.setText("Age : ");

        lblStudentGender.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblStudentGender.setText("Gender : ");

        txtProfessorGender.setEnabled(false);
        txtProfessorGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProfessorGenderActionPerformed(evt);
            }
        });

        lblStudentEmail.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblStudentEmail.setText("E-mail Id : ");

        btnBack.setBackground(new java.awt.Color(255, 204, 204));
        btnBack.setText("<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        cbShowPassword.setText("Show Password");
        cbShowPassword.setEnabled(false);
        cbShowPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbShowPasswordMouseClicked(evt);
            }
        });

        txtProfessorPassword.setEditable(false);
        txtProfessorPassword.setEnabled(false);
        txtProfessorPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtProfessorPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtProfessorPasswordFocusLost(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 75, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblProfessorName, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(36, 36, 36)
                                        .addComponent(txtProfessorName, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblStudentAge, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(36, 36, 36)
                                        .addComponent(txtProfessorAge, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblStudentGender, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(36, 36, 36)
                                    .addComponent(txtProfessorGender, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblStudentEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(36, 36, 36)
                                    .addComponent(txtProfessorEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblStudentContact, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(36, 36, 36)
                                    .addComponent(txtProfessorContact, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblStudentUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(36, 36, 36)
                                    .addComponent(txtProfessorUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblStudentPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(227, 227, 227))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblStudentCountry, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                                    .addComponent(lblStudentState, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblStudentCity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtProfessorCountry, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                                        .addComponent(txtProfessorState, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                                        .addComponent(txtProfessorCity, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                                        .addComponent(txtProfessorPassword))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(3, 3, 3))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33)
                .addComponent(cbShowPassword)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtProfessorName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProfessorName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStudentAge, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProfessorAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStudentGender, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProfessorGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStudentEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProfessorEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStudentContact, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProfessorContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStudentUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProfessorUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStudentPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbShowPassword)
                    .addComponent(txtProfessorPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStudentCity, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProfessorCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStudentState, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProfessorState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStudentCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProfessorCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(117, 117, 117))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtProfessorEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProfessorEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProfessorEmailActionPerformed

    private void txtProfessorContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProfessorContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProfessorContactActionPerformed

    private void txtProfessorUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProfessorUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProfessorUserNameActionPerformed

    private void txtProfessorCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProfessorCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProfessorCityActionPerformed

    private void txtProfessorStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProfessorStateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProfessorStateActionPerformed

    private void txtProfessorCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProfessorCountryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProfessorCountryActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        btnUpdate.setEnabled(false);
        btnSave.setEnabled(true);

        txtProfessorName.setEnabled(true);
        txtProfessorAge.setEnabled(true);
        txtProfessorGender.setEnabled(true);
        txtProfessorEmail.setEnabled(true);
        txtProfessorContact.setEnabled(true);
        txtProfessorUserName.setEnabled(true);
        txtProfessorPassword.setEnabled(true);
        txtProfessorPassword.setEditable(true);
        txtProfessorCity.setEnabled(true);
        txtProfessorState.setEnabled(true);
        cbShowPassword.setEnabled(true);
        txtProfessorCountry.setEnabled(true);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        if (txtProfessorUserName.getText().equals("") || txtProfessorPassword.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Username and Password are mandatory.");

        } else {
            btnSave.setEnabled(false);
            btnUpdate.setEnabled(true);

            txtProfessorName.setEnabled(false);
            txtProfessorAge.setEnabled(false);
            txtProfessorGender.setEnabled(false);
            txtProfessorEmail.setEnabled(false);
            txtProfessorContact.setEnabled(false);
            txtProfessorUserName.setEnabled(false);
            txtProfessorPassword.setEnabled(false);
            txtProfessorCity.setEnabled(false);
            txtProfessorState.setEnabled(false);
            txtProfessorCountry.setEnabled(false);
            cbShowPassword.setEnabled(false);
//txtProfessorRepo.setEnabled(false);

            String name = txtProfessorName.getText();
            String age = txtProfessorAge.getText();
            String gender = txtProfessorGender.getText();
            String email = txtProfessorEmail.getText();
            String contact = txtProfessorContact.getText();
            String username = txtProfessorUserName.getText();
            String password = txtProfessorPassword.getText();
            String city = txtProfessorCity.getText();
            String state = txtProfessorState.getText();
            String country = txtProfessorCountry.getText();
//        String repo=txtProfessorRepo.getText();
            //professorModel professor = professorDirectory.searchProfessor(txtProfessorName.getName());
            // Professor professor=professorDirectory.searchProfessor(username);

            if (!isValidPassword(password)) {
                JOptionPane.showMessageDialog(null, "Password must be at least 6 characters long, include at least 1 special character and 1 number.");
                return;
            }
            professor.setName(name);
            professor.setAge(age);
            professor.setGender(gender);

            professor.setEmail(email);
            professor.setContact(contact);
            professor.setUsername(username);
            professor.setPassword(password);
            professor.setCity(city);
            professor.setState(state);
            professor.setCountry(country);
            //  professor.setReputation(repo);
            JOptionPane.showMessageDialog(null, "Professor Updated Successfully.");
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtProfessorNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProfessorNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProfessorNameActionPerformed

    private void txtProfessorAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProfessorAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProfessorAgeActionPerformed

    private void txtProfessorGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProfessorGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProfessorGenderActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        workAreaContainer.remove(this);
        CardLayout layout = (CardLayout) workAreaContainer.getLayout();
        layout.previous(workAreaContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void cbShowPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbShowPasswordMouseClicked
        if (cbShowPassword.isSelected()) {
            txtProfessorPassword.setEchoChar((char) 0); // Show the password as plain text
            cbShowPassword.setText("Hide Password");
        } else {
            txtProfessorPassword.setEchoChar('*');
            cbShowPassword.setText("Show Password");
        }
    }//GEN-LAST:event_cbShowPasswordMouseClicked

    private void txtProfessorPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtProfessorPasswordFocusGained
        // TODO add your handling code here:
        if (txtProfessorPassword.getText().equals("(Password encrypted)")) {
            txtProfessorPassword.setText("");
            txtProfessorPassword.setEchoChar('*');
        }
    }//GEN-LAST:event_txtProfessorPasswordFocusGained

    private void txtProfessorPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtProfessorPasswordFocusLost
        // TODO add your handling code here:
        if (txtProfessorPassword.getText().isEmpty()) {
            txtProfessorPassword.setText("(Password encrypted)");
            txtProfessorPassword.setEchoChar((char) 0);
        }
    }//GEN-LAST:event_txtProfessorPasswordFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JCheckBox cbShowPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblProfessorName;
    private javax.swing.JLabel lblStudentAge;
    private javax.swing.JLabel lblStudentCity;
    private javax.swing.JLabel lblStudentContact;
    private javax.swing.JLabel lblStudentCountry;
    private javax.swing.JLabel lblStudentEmail;
    private javax.swing.JLabel lblStudentGender;
    private javax.swing.JLabel lblStudentPassword;
    private javax.swing.JLabel lblStudentState;
    private javax.swing.JLabel lblStudentUserName;
    private javax.swing.JTextField txtProfessorAge;
    private javax.swing.JTextField txtProfessorCity;
    private javax.swing.JTextField txtProfessorContact;
    private javax.swing.JTextField txtProfessorCountry;
    private javax.swing.JTextField txtProfessorEmail;
    private javax.swing.JTextField txtProfessorGender;
    private javax.swing.JTextField txtProfessorName;
    private javax.swing.JPasswordField txtProfessorPassword;
    private javax.swing.JTextField txtProfessorState;
    private javax.swing.JTextField txtProfessorUserName;
    // End of variables declaration//GEN-END:variables

    private boolean isValidPassword(String password) {
        if (password.length() < 6) {
            return false;
        }
        boolean hasNum = password.matches(".*\\d.*");
        boolean hasSpecial = !password.matches("[A-Za-z0-9]*");
        return hasNum && hasSpecial;
    }
}
