/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.Professor.ui;

import Business.Professor.model.Professor;
import Business.Professor.model.ProfessorDirectory;
import Business.Student.model.StudentDirectory;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Hemant
 */
public class ProfessorHomePageJPanel extends javax.swing.JPanel {

    //This variable stores JPanel workAreaContainer
    private JPanel workAreaContainer;
    
    //This variable stores professorDirectory
    private ProfessorDirectory professorDirectory;

    
    //This variable stores professor
    private Professor professor;
    
     //This variable stores student directory
    private StudentDirectory studentDirectory;
    /**
     * Creates new form ProfessorHomePageJPanel
     */
    public ProfessorHomePageJPanel() {
        initComponents();
    }
    
     public ProfessorHomePageJPanel(JPanel workAreaContainer,Professor professor, ProfessorDirectory professorDirectory,StudentDirectory studentDirectory) {
        initComponents();
        this.workAreaContainer = workAreaContainer;
        this.professor=professor;
        this.professorDirectory = professorDirectory;
        this.studentDirectory=studentDirectory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnViewUpdateProf = new javax.swing.JButton();
        btnAddCourseProf = new javax.swing.JButton();
        btnHistoryProf = new javax.swing.JButton();
        btnScheduleProf = new javax.swing.JButton();
        btnStudentGradesProf = new javax.swing.JButton();
        btnFeedbackOfStuentProf = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));

        btnViewUpdateProf.setText("View/Update Profile");
        btnViewUpdateProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewUpdateProfActionPerformed(evt);
            }
        });

        btnAddCourseProf.setText("Add Course");
        btnAddCourseProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCourseProfActionPerformed(evt);
            }
        });

        btnHistoryProf.setText("History");
        btnHistoryProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoryProfActionPerformed(evt);
            }
        });

        btnScheduleProf.setText("Schedule");
        btnScheduleProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnScheduleProfActionPerformed(evt);
            }
        });

        btnStudentGradesProf.setText("Students Grade");
        btnStudentGradesProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentGradesProfActionPerformed(evt);
            }
        });

        btnFeedbackOfStuentProf.setText("Feedback of students");
        btnFeedbackOfStuentProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFeedbackOfStuentProfActionPerformed(evt);
            }
        });

        btnLogOut.setText("Logout");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnStudentGradesProf, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnHistoryProf, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnViewUpdateProf, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAddCourseProf, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnScheduleProf, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnFeedbackOfStuentProf, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(180, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewUpdateProf, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddCourseProf, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHistoryProf, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnScheduleProf, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStudentGradesProf, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFeedbackOfStuentProf, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89)
                .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(330, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnFeedbackOfStuentProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFeedbackOfStuentProfActionPerformed
        StudentFeedbacksJPanel panel = new StudentFeedbacksJPanel(workAreaContainer,professor,studentDirectory);
        workAreaContainer.add("StudentFeedbacksJPanel", panel);
        CardLayout layout = (CardLayout) workAreaContainer.getLayout();
        layout.next(workAreaContainer); 
    }//GEN-LAST:event_btnFeedbackOfStuentProfActionPerformed

    private void btnViewUpdateProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewUpdateProfActionPerformed
        ProfessorViewUpdateJPanel panel = new ProfessorViewUpdateJPanel(workAreaContainer,professor, professorDirectory);
        workAreaContainer.add("ProfessorViewUpdateJPanel", panel);
        CardLayout layout = (CardLayout) workAreaContainer.getLayout();
        layout.next(workAreaContainer);
    }//GEN-LAST:event_btnViewUpdateProfActionPerformed

    private void btnAddCourseProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCourseProfActionPerformed
         AddCourseJPanel panel = new AddCourseJPanel(workAreaContainer,professor, professorDirectory);
        workAreaContainer.add("AddCourseJPanel", panel);
        CardLayout layout = (CardLayout) workAreaContainer.getLayout();
        layout.next(workAreaContainer);
    }//GEN-LAST:event_btnAddCourseProfActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        workAreaContainer.remove(this);
        CardLayout layout = (CardLayout) workAreaContainer.getLayout();
        layout.previous(workAreaContainer);
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnScheduleProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnScheduleProfActionPerformed
        ScheduleJPanel panel = new ScheduleJPanel(workAreaContainer,professor);
        workAreaContainer.add("ScheduleJPanel", panel);
        CardLayout layout = (CardLayout) workAreaContainer.getLayout();
        layout.next(workAreaContainer);
    }//GEN-LAST:event_btnScheduleProfActionPerformed

    private void btnHistoryProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoryProfActionPerformed
         HistoryJPanel panel = new HistoryJPanel(workAreaContainer,professor);
        workAreaContainer.add("HistoryJPanel", panel);
        CardLayout layout = (CardLayout) workAreaContainer.getLayout();
        layout.next(workAreaContainer);
    }//GEN-LAST:event_btnHistoryProfActionPerformed

    private void btnStudentGradesProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentGradesProfActionPerformed
        StudentGradesJPanel panel = new StudentGradesJPanel(workAreaContainer,professor,professorDirectory, studentDirectory);
        workAreaContainer.add("ScheduleJPanel", panel);
        CardLayout layout = (CardLayout) workAreaContainer.getLayout();
        layout.next(workAreaContainer);
    }//GEN-LAST:event_btnStudentGradesProfActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCourseProf;
    private javax.swing.JButton btnFeedbackOfStuentProf;
    private javax.swing.JButton btnHistoryProf;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnScheduleProf;
    private javax.swing.JButton btnStudentGradesProf;
    private javax.swing.JButton btnViewUpdateProf;
    // End of variables declaration//GEN-END:variables
}
