/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.Student.ui;

import Business.Professor.model.Professor;
import Business.Professor.model.ProfessorDirectory;
import Business.Student.model.Student;
import Business.Student.model.StudentDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Hemant
 */
public class StudentUpdateJPanel extends javax.swing.JPanel {

         //This variable stores JPanel workAreaContainer
    private JPanel workAreaContainer;
    
    //This variable stores student directory
    private StudentDirectory studentDirectory;
    
    //This variable stores professor directory
    private ProfessorDirectory professorDirectory;
    
    //This variable stores Student
    private Student student;
    
    /**
    /**
     * Creates new form StudentUpdateJPanel
     */
    public StudentUpdateJPanel(JPanel workAreaContainer,Student student,StudentDirectory studentDirectory) {
        initComponents();
        this.workAreaContainer=workAreaContainer;
        this.studentDirectory=studentDirectory;
        this.student=student;
        
        txtStudentName.setText(student.getName());
        txtStudentAge.setText(student.getAge());
        txtStudentGender.setText(student.getGender());
        txtStudentEmail.setText(student.getEmail());
        txtStudentContact.setText(student.getContact());
        txtStudentUserName.setText(student.getUsername());
        txtStudentNUID.setText(student.getNUID());
        txtStudentPassword.setText("(Password encrypted)");
        txtStudentPassword.setEchoChar((char) 0);
        txtStudentCity.setText(student.getCity());
        txtStudentProgram.setText(student.getProgram());
        txtStudentTerm.setText(student.getAdmissionTerm());
        txtStudentState.setText(student.getState());
        txtStudentCountry.setText(student.getCountry());
        txtStudentAddress.setText(student.getAddress());
        txtStudentCode.setText(String.valueOf(student.getCode()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtStudentCity = new javax.swing.JTextField();
        lblStudentState = new javax.swing.JLabel();
        txtStudentAge = new javax.swing.JTextField();
        txtStudentState = new javax.swing.JTextField();
        lblStudentGender = new javax.swing.JLabel();
        lblStudentCountry = new javax.swing.JLabel();
        txtStudentGender = new javax.swing.JTextField();
        txtStudentCountry = new javax.swing.JTextField();
        lblStudentEmail = new javax.swing.JLabel();
        lblStudentName13 = new javax.swing.JLabel();
        txtStudentEmail = new javax.swing.JTextField();
        txtStudentCode = new javax.swing.JTextField();
        lblStudentContact = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        txtStudentContact = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        lblStudentTerm = new javax.swing.JLabel();
        txtStudentTerm = new javax.swing.JTextField();
        lblStudentProgram = new javax.swing.JLabel();
        txtStudentProgram = new javax.swing.JTextField();
        lblStudentNUID = new javax.swing.JLabel();
        txtStudentNUID = new javax.swing.JTextField();
        lblStudentUserName = new javax.swing.JLabel();
        txtStudentUserName = new javax.swing.JTextField();
        lblStudentPassword = new javax.swing.JLabel();
        lblStudentAddress = new javax.swing.JLabel();
        txtStudentAddress = new javax.swing.JTextField();
        lblStudentCity = new javax.swing.JLabel();
        lblStudentAge = new javax.swing.JLabel();
        txtStudentName = new javax.swing.JTextField();
        lblStudentName = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        cbShowPassword = new javax.swing.JCheckBox();
        txtStudentPassword = new javax.swing.JPasswordField();

        setBackground(new java.awt.Color(204, 204, 204));

        txtStudentCity.setEnabled(false);
        txtStudentCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStudentCityActionPerformed(evt);
            }
        });

        lblStudentState.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblStudentState.setText("State : ");

        txtStudentAge.setEnabled(false);
        txtStudentAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStudentAgeActionPerformed(evt);
            }
        });

        txtStudentState.setEnabled(false);
        txtStudentState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStudentStateActionPerformed(evt);
            }
        });

        lblStudentGender.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblStudentGender.setText("Gender : ");

        lblStudentCountry.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblStudentCountry.setText("Country : ");

        txtStudentGender.setEnabled(false);
        txtStudentGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStudentGenderActionPerformed(evt);
            }
        });

        txtStudentCountry.setEnabled(false);
        txtStudentCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStudentCountryActionPerformed(evt);
            }
        });

        lblStudentEmail.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblStudentEmail.setText("E-mail Id : ");

        lblStudentName13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblStudentName13.setText("Code : ");

        txtStudentEmail.setEnabled(false);
        txtStudentEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStudentEmailActionPerformed(evt);
            }
        });

        txtStudentCode.setEnabled(false);
        txtStudentCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStudentCodeActionPerformed(evt);
            }
        });

        lblStudentContact.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblStudentContact.setText("Contact Number : ");

        btnSave.setText("Save");
        btnSave.setEnabled(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        txtStudentContact.setEnabled(false);
        txtStudentContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStudentContactActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        lblStudentTerm.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblStudentTerm.setText("Admission term : ");

        txtStudentTerm.setEnabled(false);
        txtStudentTerm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStudentTermActionPerformed(evt);
            }
        });

        lblStudentProgram.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblStudentProgram.setText("Program : ");

        txtStudentProgram.setEnabled(false);
        txtStudentProgram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStudentProgramActionPerformed(evt);
            }
        });

        lblStudentNUID.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblStudentNUID.setText("NUID : ");

        txtStudentNUID.setEnabled(false);
        txtStudentNUID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStudentNUIDActionPerformed(evt);
            }
        });

        lblStudentUserName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblStudentUserName.setText("User Name : ");

        txtStudentUserName.setEnabled(false);
        txtStudentUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStudentUserNameActionPerformed(evt);
            }
        });

        lblStudentPassword.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblStudentPassword.setText("Password : ");

        lblStudentAddress.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblStudentAddress.setText("Address : ");

        txtStudentAddress.setEnabled(false);
        txtStudentAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStudentAddressActionPerformed(evt);
            }
        });

        lblStudentCity.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblStudentCity.setText("City : ");

        lblStudentAge.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblStudentAge.setText("Age : ");

        txtStudentName.setEnabled(false);
        txtStudentName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStudentNameActionPerformed(evt);
            }
        });

        lblStudentName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblStudentName.setText("Name : ");

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Update Profile");

        btnBack.setText("<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        cbShowPassword.setText("Show Password");
        cbShowPassword.setEnabled(false);
        cbShowPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbShowPasswordMouseClicked(evt);
            }
        });
        cbShowPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbShowPasswordActionPerformed(evt);
            }
        });

        txtStudentPassword.setEnabled(false);
        txtStudentPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtStudentPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtStudentPasswordFocusLost(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 757, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(36, 36, 36)
                                        .addComponent(txtStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblStudentAge, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblStudentGender, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(36, 36, 36)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtStudentGender, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtStudentAge, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblStudentEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblStudentContact, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblStudentTerm, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblStudentProgram, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblStudentNUID, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(36, 36, 36)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(2, 2, 2)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtStudentNUID, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtStudentProgram, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtStudentTerm, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(txtStudentContact, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtStudentEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cbShowPassword)
                                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(74, 74, 74)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblStudentName13, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblStudentAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lblStudentCity, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lblStudentState, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lblStudentCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGap(36, 36, 36)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtStudentCode, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtStudentCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtStudentState, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtStudentCity, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtStudentAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblStudentPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lblStudentUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(36, 36, 36)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(2, 2, 2)
                                                    .addComponent(txtStudentUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(txtStudentPassword))))))))
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(464, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblStudentUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtStudentUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblStudentPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtStudentPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblStudentAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtStudentAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblStudentCity, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtStudentCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblStudentState, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtStudentState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblStudentCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtStudentCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblStudentName13, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtStudentCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbShowPassword))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblStudentAge, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtStudentAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblStudentGender, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtStudentGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblStudentEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtStudentEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblStudentContact, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtStudentContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblStudentTerm, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtStudentTerm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblStudentProgram, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtStudentProgram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblStudentNUID, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtStudentNUID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(68, 68, 68)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtStudentCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStudentCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStudentCityActionPerformed

    private void txtStudentAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStudentAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStudentAgeActionPerformed

    private void txtStudentStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStudentStateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStudentStateActionPerformed

    private void txtStudentGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStudentGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStudentGenderActionPerformed

    private void txtStudentCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStudentCountryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStudentCountryActionPerformed

    private void txtStudentEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStudentEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStudentEmailActionPerformed

    private void txtStudentCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStudentCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStudentCodeActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        btnSave.setEnabled(false);
        btnUpdate.setEnabled(true);

        txtStudentName.setEnabled(false);
        txtStudentAge.setEnabled(false);
        txtStudentGender.setEnabled(false);
        txtStudentEmail.setEnabled(false);
        txtStudentContact.setEnabled(false);
        txtStudentTerm.setEnabled(false);
        txtStudentProgram.setEnabled(false);
        txtStudentUserName.setEnabled(false);
        txtStudentPassword.setEnabled(false);
        txtStudentNUID.setEnabled(false);
        txtStudentAddress.setEnabled(false);
        txtStudentCity.setEnabled(false);
        txtStudentState.setEnabled(false);
        txtStudentCode.setEnabled(false);
        txtStudentCountry.setEnabled(false);
        cbShowPassword.setEnabled(false);

        String name = txtStudentName.getText();
        String age = txtStudentAge.getText();
        String gender = txtStudentGender.getText();
        String email = txtStudentEmail.getText();
        String contact = txtStudentContact.getText();
        String admissionTerm = txtStudentTerm.getText();
        String NUID = txtStudentNUID.getText();
        String username = txtStudentUserName.getText();
        String password = txtStudentPassword.getText();
        String address = txtStudentAddress.getText();
        String city = txtStudentCity.getText();
        String state = txtStudentState.getText();
        String country = txtStudentCountry.getText();
        int code = Integer.parseInt(txtStudentCode.getText());
        String program = txtStudentProgram.getText();
        
        if (!isValidPassword(password)) {
                JOptionPane.showMessageDialog(null, "Password must be at least 6 characters long, include at least 1 special character and 1 number.");
                return;
            }

        Student student = studentDirectory.searchStudent(txtStudentNUID.getText());
        student.setName(name);
        student.setAge(age);
        student.setGender(gender);
        student.setEmail(email);
        student.setContact(contact);
        student.setAdmissionTerm(admissionTerm);
        student.setNUID(NUID);
        student.setUsername(username);
        student.setPassword(password);
        student.setAddress(address);
        student.setCity(city);
        student.setState(state);
        student.setCountry(country);
        student.setCode(code);
        student.setProgram(program);
        txtStudentPassword.setText("(Password encrypted)");
        txtStudentPassword.setEchoChar((char) 0);
        
  JOptionPane.showMessageDialog(null, "Student Updated Successfully.");
  
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtStudentContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStudentContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStudentContactActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        btnUpdate.setEnabled(false);
        btnSave.setEnabled(true);

        txtStudentName.setEnabled(true);
        txtStudentAge.setEnabled(true);
        txtStudentGender.setEnabled(true);
        txtStudentEmail.setEnabled(true);
        txtStudentContact.setEnabled(true);
        txtStudentTerm.setEnabled(true);
        txtStudentProgram.setEnabled(true);
        txtStudentUserName.setEnabled(true);
        txtStudentPassword.setEnabled(true);
        txtStudentNUID.setEnabled(true);
        txtStudentAddress.setEnabled(true);
        txtStudentCity.setEnabled(true);
        txtStudentState.setEnabled(true);
        txtStudentCode.setEnabled(true);
        txtStudentCountry.setEnabled(true);
        cbShowPassword.setEnabled(true);

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void txtStudentTermActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStudentTermActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStudentTermActionPerformed

    private void txtStudentProgramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStudentProgramActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStudentProgramActionPerformed

    private void txtStudentNUIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStudentNUIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStudentNUIDActionPerformed

    private void txtStudentUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStudentUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStudentUserNameActionPerformed

    private void txtStudentAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStudentAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStudentAddressActionPerformed

    private void txtStudentNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStudentNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStudentNameActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        workAreaContainer.remove(this);
        CardLayout layout = (CardLayout) workAreaContainer.getLayout();
        layout.previous(workAreaContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void cbShowPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbShowPasswordMouseClicked
       if(cbShowPassword.isSelected()){
                     txtStudentPassword.setEchoChar((char) 0); // Show the password as plain text
                    cbShowPassword.setText("Hide Password");
                } else {
                    txtStudentPassword.setEchoChar('*');
                    cbShowPassword.setText("Show Password");
                }
    }//GEN-LAST:event_cbShowPasswordMouseClicked

    private void txtStudentPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtStudentPasswordFocusGained
        // TODO add your handling code here:
        if(txtStudentPassword.getText().equals("(Password encrypted)")){
            txtStudentPassword.setText("");
            txtStudentPassword.setEchoChar('*');
        }
    }//GEN-LAST:event_txtStudentPasswordFocusGained

    private void txtStudentPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtStudentPasswordFocusLost
        // TODO add your handling code here:
        if(txtStudentPassword.getText().isEmpty()){
            txtStudentPassword.setText("(Password encrypted)");
            txtStudentPassword.setEchoChar((char) 0);
        }
    }//GEN-LAST:event_txtStudentPasswordFocusLost

    private void cbShowPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbShowPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbShowPasswordActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JCheckBox cbShowPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblStudentAddress;
    private javax.swing.JLabel lblStudentAge;
    private javax.swing.JLabel lblStudentCity;
    private javax.swing.JLabel lblStudentContact;
    private javax.swing.JLabel lblStudentCountry;
    private javax.swing.JLabel lblStudentEmail;
    private javax.swing.JLabel lblStudentGender;
    private javax.swing.JLabel lblStudentNUID;
    private javax.swing.JLabel lblStudentName;
    private javax.swing.JLabel lblStudentName13;
    private javax.swing.JLabel lblStudentPassword;
    private javax.swing.JLabel lblStudentProgram;
    private javax.swing.JLabel lblStudentState;
    private javax.swing.JLabel lblStudentTerm;
    private javax.swing.JLabel lblStudentUserName;
    private javax.swing.JTextField txtStudentAddress;
    private javax.swing.JTextField txtStudentAge;
    private javax.swing.JTextField txtStudentCity;
    private javax.swing.JTextField txtStudentCode;
    private javax.swing.JTextField txtStudentContact;
    private javax.swing.JTextField txtStudentCountry;
    private javax.swing.JTextField txtStudentEmail;
    private javax.swing.JTextField txtStudentGender;
    private javax.swing.JTextField txtStudentNUID;
    private javax.swing.JTextField txtStudentName;
    private javax.swing.JPasswordField txtStudentPassword;
    private javax.swing.JTextField txtStudentProgram;
    private javax.swing.JTextField txtStudentState;
    private javax.swing.JTextField txtStudentTerm;
    private javax.swing.JTextField txtStudentUserName;
    // End of variables declaration//GEN-END:variables

    private boolean isValidPassword(String password) {
        if (password.length() < 6) {
            return false;
        }
        boolean hasNum = password.matches(".*\\d.*");
        boolean hasSpecial = !password.matches("[A-Za-z0-9]*");
        return hasNum && hasSpecial;
    }
}
